### ISSUE TITLE
Creating Footer of the website

### ISSUE THREAD

**Issue by Kritika745** [AndrewThompson999/pizza-house#2]
Hey @AndrewThompson999 I can create footer of this website please assign me this

**Comment by AndrewThompson999** [comment]
@Kritika745 great! Feel free! Waiting your pull requests!

**Comment by Kritika745** [comment]
Please assign me this issue and add labels of hactoberfest-accepted, gssoc-ext and level2

**Comment by AndrewThompson999** [comment]
@Kritika745 assigned. Added label `hacktoberfest`, when you'll make PR and I'll approve it I'll give label `hacktoberfest-accepted`
